import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  ColorSchemeScript,
  MantineProvider,
  MantineProviderProps,
  MantineTheme,
  MantineThemeOverride,
  createTheme,
  mergeThemeOverrides,
} from "@mantine/core";
import MantineThemeConfig from "@/config/MantineThemeConfig";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"
    // className="dark"
    >
      <head>
        <ColorSchemeScript />
      </head>
      <body className={''}>
        <MantineProvider theme={MantineThemeConfig} withCssVariables>
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
